### ISSUE TITLE
关于心跳机制

### ISSUE THREAD

**Issue by cheny-alf** [Gloduck/NettyRpc#6]
为什么客户端发的心跳包，服务端会读不出来呢，报了错误的消息长度

**Comment by Gloduck** [comment]
能贴一个错误日志吗，看描述可能是解码消息的时候出现错误了。

**Comment by cheny-alf** [comment]
![image](https://user-images.githubusercontent.com/71162267/167044832-e6e85918-3361-45db-a260-a491deb5f74c.png)
顺便想问下，如何体现负载均衡的效果呢，我在本地开多个server端，并没有把请求分发到不同的server上。

**Comment by cheny-alf** [comment]
![image](https://user-images.githubusercontent.com/71162267/167044973-0b53ed73-81e0-4394-9fb0-be0fa89a389b.png)

**Comment by Gloduck** [comment]
是不是你用了iphash了。这个是根据ip地址哈希来的。你如果本机的话ip一样最后选择的就是同一个实例。调试的话可以在切面打个断点。

**Comment by cheny-alf** [comment]
> 解码

调用方法的时候是可以的，就是心跳包是有问题的

**Comment by cheny-alf** [comment]
> 是不是你用了iphash了。这个是根据ip地址哈希来的。你如果本机的话ip一样最后选择的就是同一个实例。调试的话可以在切面打个断点。

确实是这么回事， 感谢
